[package]
name = "attendance_cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.57", features = ["derive"] }
ron = "0.12.0"
serde = { version = "1.0.228", features = ["derive"] }

[[bin]]
name = "attendance"
path = "src/main.rs"